"""Regenerate every artefact in reports/ from a clean slate, in one command.

    python scripts/run_demo.py --posture crisis_mode   # deterministic core, no key
    python scripts/run_demo.py --live                  # real API calls

Nothing this writes is committed. reports/ is generated output and is gitignored:
a report checked into the tree is a run frozen at whatever the code did that day,
and it goes on looking current long after it stops being true.

Without a key there is no posture advisor, so --posture is required. The script will
not pick the company's values on its behalf.

What it does, in order:

    1. reseed data/history + state/ from the fixed seed
    2. delete the generated reports, including the append-only decision log
    3. run batches 42, 43, 44 IN SEQUENCE, so fairness debt carries between them
    4. posture audit across the sequence
    5. planted-conflict eval
    6. stability, N reruns of batch 42

Step 2 deletes files. They are all generated by steps 1 and 3-6 and nothing else
writes to them, but it is a delete and it is named as one. `--keep-log` skips it.

The decision log is append-only *within* a demo, which is what makes the audit
meaningful; it is truncated *between* demos, because an audit that silently averaged
this run together with four earlier rehearsals would be reporting a number nobody
could reproduce.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from triage import audit as audit_mod  # noqa: E402
from triage import evaluate as evaluate_mod  # noqa: E402
from triage import paths, report as report_mod  # noqa: E402
from triage import stability as stability_mod  # noqa: E402
from triage.pipeline import Context, RunOptions, run_batch  # noqa: E402

GENERATED = ("*.md", "*.json", "decision_log.jsonl")


def banner(text: str) -> None:
    print(f"\n{'=' * 78}\n{text}\n{'=' * 78}")


def reseed() -> None:
    banner("1. reseed history and state from the fixed seed")
    subprocess.run([sys.executable, str(ROOT / "scripts" / "seed_history.py")], check=True)


def clear_reports(keep_log: bool) -> None:
    banner("2. clear generated reports")
    reports = paths.reports_dir()
    reports.mkdir(parents=True, exist_ok=True)
    for pattern in GENERATED:
        for path in sorted(reports.glob(pattern)):
            if keep_log and path.name == "decision_log.jsonl":
                print(f"   keeping {path.name}")
                continue
            path.unlink()
            print(f"   removed {path.relative_to(ROOT)}")


def batches() -> list[Path]:
    found = list(paths.eval_dir().glob("batch_*.json"))
    return sorted(found, key=lambda p: json.loads(p.read_text(encoding="utf-8"))["batch_id"])


def run_sequence(use_llm: bool, posture: str | None) -> None:
    banner("3. run every batch in sequence, fairness debt carrying over")
    for path in batches():
        ctx = Context.load(path)
        report = run_batch(
            ctx,
            RunOptions(posture=posture, use_llm=use_llm, assume_yes=True, persist_state=True),
        )
        md, js = report_mod.write(report)
        served = [r.ticket_id for r in report.ordering.ranked if r.served]
        print(
            f"\n   batch {report.batch_id}: posture {report.posture}, "
            f"{len(report.conflicts)} conflicts, "
            f"{len(report.ordering.overrides)} charter override(s)"
        )
        print(f"     served: {', '.join(served)}")
        if report.degraded_stages:
            print(f"     degraded: {len(report.degraded_stages)} stage(s)")
        print(f"     wrote {md.relative_to(ROOT)}, {js.relative_to(ROOT)}")


def run_audit() -> None:
    banner("4. posture audit across the sequence")
    result = audit_mod.audit(audit_mod.load_decisions())
    print(audit_mod.render(result))
    out = paths.reports_dir() / "posture_audit.json"
    out.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"\n   wrote {out.relative_to(ROOT)}")


def run_eval(use_llm: bool) -> None:
    banner("5. planted-conflict eval")
    result = evaluate_mod.evaluate(use_llm=use_llm)
    print(evaluate_mod.render(result))
    print(f"\n   wrote {evaluate_mod.write(result).relative_to(ROOT)}")


def run_stability(runs: int, use_llm: bool, posture: str | None) -> None:
    banner(f"6. stability, {runs} reruns of batch 42")
    result = stability_mod.measure(
        batch_path=batches()[0], runs=runs, posture=posture, use_llm=use_llm
    )
    print(stability_mod.render(result))
    print(f"\n   wrote {stability_mod.write(result).relative_to(ROOT)}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--live", action="store_true", help="real API calls; needs ANTHROPIC_API_KEY")
    ap.add_argument("--posture", help="posture to run under; required without --live")
    ap.add_argument("--runs", type=int, default=10, help="stability reruns (default 10)")
    ap.add_argument("--keep-log", action="store_true", help="do not truncate the decision log")
    args = ap.parse_args()

    if not args.live and not args.posture:
        ap.error(
            "--posture is required without --live: with no key there is no advisor, "
            "and defaulting to `balanced` would be this script picking the company's "
            "values and calling the choice neutral. Postures are in config/postures/."
        )

    use_llm = bool(args.live)
    print(f"regenerating artefacts - mode: {'live API' if use_llm else 'deterministic core only'}")

    reseed()
    clear_reports(args.keep_log)
    run_sequence(use_llm, args.posture)
    run_audit()
    run_eval(use_llm)
    run_stability(args.runs, use_llm, args.posture)

    banner("done")
    print(f"   artefacts in {paths.reports_dir().relative_to(ROOT)}/ (generated, not committed)")
    if not use_llm:
        print("\n   ! This was a deterministic run. Every report carries a degraded-run")
        print("     banner naming the stages that did not execute. That is the honest")
        print("     state of things without an API key, not a formality.")


if __name__ == "__main__":
    main()
